### ISSUE TITLE
Maven isn't installed

### ISSUE THREAD

**Issue by jpkrohling** [katacoda-scenarios/opentracing-scenarios#4]
Thanks @kerylefondji for reporting this!

Some recent update to the base image has removed support for Maven, breaking the OpenTracing scenarios:

![image](https://user-images.githubusercontent.com/13387/47146457-5c63b600-d2cc-11e8-9c44-ec6fff2a77bf.png)

This can be reproduced on the OpenTracing Tutorial - Lesson 1, step 1.

**Comment by jpkrohling** [comment]
cc @BenHall

**Comment by BenHall** [comment]
Thanks, this was fixed yesterday.
